runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /v1/.*
  script: main.app

- url: /_tasks/.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest

skip_files:
- ^(storage)/.*
